{
 "title": "Spark: Jobs Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Allocated vs Guarantee Dispatcher-0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_allocator_role_quota_offered_or_allocated{resource=\"cpus\", role=\"dispatcher-mixed-0-dispatcher-role\"}"
    },
    {
     "expr": "mesos_master_allocator_role_quota_guarantee{resource=\"cpus\", role=\"dispatcher-mixed-0-dispatcher-role\"}"
    },
    {}
   ]
  },
  {
   "title": "Allocated vs Guaranteed CPU all agents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_master_allocator_role_quota_offered_or_allocated{resource=\"cpus\"}"
    },
    {
     "expr": "mesos_master_allocator_role_quota_guarantee{resource=\"cpus\"}"
    }
   ]
  },
  {
   "title": "Number of Dispatchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_cluster_driver_launched)"
    }
   ]
  },
  {
   "title": "Number of Jobs Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_cluster_executor_count)"
    }
   ]
  },
  {
   "title": "Number of Jobs by App Name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_cluster_executor_count{task_name=~\".*Kafka.*\"})",
     "legendFormat": "Kafka Spark-Streaming"
    },
    {
     "expr": "count(spark_mesos_cluster_executor_count{task_name=~\".*monte.*\"})",
     "legendFormat": "Batch Monte-Carlo"
    },
    {
     "expr": "count(spark_mesos_cluster_executor_count{task_name=~\".*image.*\"})",
     "legendFormat": "Batch GPU Image-Recognition"
    }
   ]
  },
  {
   "title": "Number of Drivers Reporting Metrics vs. Jobs Reported by Dispatchers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(spark_mesos_cluster_executor_count)",
     "legendFormat": "Number of drivers reporting"
    },
    {
     "expr": "sum(spark_mesos_cluster_driver_launched)",
     "legendFormat": "Number of jobs reported by dispatchers"
    }
   ]
  },
  {
   "title": "Avg. Queue Depth per Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_driver_waiting)"
    }
   ]
  },
  {
   "title": "Avg. Number of Jobs per Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_driver_launched)"
    }
   ]
  },
  {
   "title": "Avg. Number of Executors per Job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_executor_count)"
    }
   ]
  },
  {
   "title": "Avg. Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_driver_launch_to_finish_state_finished_mean) / 60000"
    }
   ]
  },
  {
   "title": "Job Success Rate",
   "type": "graph",
   "description": "% of jobs that finish successfully",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_mesos_cluster_driver_finished_count_mesos_state_task_finished) / (sum(spark_mesos_cluster_driver_finished_count_mesos_state_task_finished) + sum(spark_mesos_cluster_driver_finished_count_mesos_state_task_lost) + sum(spark_mesos_cluster_driver_finished_count_mesos_state_task_failed))"
    }
   ]
  },
  {
   "title": "Avg. Job Launch Time (sec.)",
   "type": "graph",
   "description": "Driver start to all executors launched",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_executor_start_to_all_launched_mean) / 1000"
    }
   ]
  },
  {
   "title": "Avg. Number of Queued Retry Jobs per Dispatcher",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(spark_mesos_cluster_driver_retry)"
    }
   ]
  },
  {
   "title": "Job Launch Time Std. Dev. (sec.)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stddev(spark_mesos_cluster_executor_start_to_all_launched_mean) / 1000"
    }
   ]
  }
 ]
}